//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_Articles_T_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Users), "T_Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_Articles), true)]
[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_Categories_T_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Users), "T_Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_Categories), true)]
[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_Action_Role_T_Action", "T_Action", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Action), "T_Action_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_Action_Role), true)]
[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_Action_Role_T_Role", "T_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Role), "T_Action_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_Action_Role), true)]
[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_User_Role_T_Role", "T_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Role), "T_User_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_User_Role), true)]
[assembly: EdmRelationshipAttribute("DB_CMSModel", "FK_T_User_Role_T_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(G1mist.CMS.Modal.T_Users), "T_User_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(G1mist.CMS.Modal.T_User_Role), true)]

#endregion

namespace G1mist.CMS.Modal
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DB_CMSEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DB_CMSEntities”部分中的连接字符串初始化新 DB_CMSEntities 对象。
        /// </summary>
        public DB_CMSEntities() : base("name=DB_CMSEntities", "DB_CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DB_CMSEntities 对象。
        /// </summary>
        public DB_CMSEntities(string connectionString) : base(connectionString, "DB_CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DB_CMSEntities 对象。
        /// </summary>
        public DB_CMSEntities(EntityConnection connection) : base(connection, "DB_CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Articles> T_Articles
        {
            get
            {
                if ((_T_Articles == null))
                {
                    _T_Articles = base.CreateObjectSet<T_Articles>("T_Articles");
                }
                return _T_Articles;
            }
        }
        private ObjectSet<T_Articles> _T_Articles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Categories> T_Categories
        {
            get
            {
                if ((_T_Categories == null))
                {
                    _T_Categories = base.CreateObjectSet<T_Categories>("T_Categories");
                }
                return _T_Categories;
            }
        }
        private ObjectSet<T_Categories> _T_Categories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Links> T_Links
        {
            get
            {
                if ((_T_Links == null))
                {
                    _T_Links = base.CreateObjectSet<T_Links>("T_Links");
                }
                return _T_Links;
            }
        }
        private ObjectSet<T_Links> _T_Links;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Users> T_Users
        {
            get
            {
                if ((_T_Users == null))
                {
                    _T_Users = base.CreateObjectSet<T_Users>("T_Users");
                }
                return _T_Users;
            }
        }
        private ObjectSet<T_Users> _T_Users;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Action> T_Action
        {
            get
            {
                if ((_T_Action == null))
                {
                    _T_Action = base.CreateObjectSet<T_Action>("T_Action");
                }
                return _T_Action;
            }
        }
        private ObjectSet<T_Action> _T_Action;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Action_Role> T_Action_Role
        {
            get
            {
                if ((_T_Action_Role == null))
                {
                    _T_Action_Role = base.CreateObjectSet<T_Action_Role>("T_Action_Role");
                }
                return _T_Action_Role;
            }
        }
        private ObjectSet<T_Action_Role> _T_Action_Role;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Role> T_Role
        {
            get
            {
                if ((_T_Role == null))
                {
                    _T_Role = base.CreateObjectSet<T_Role>("T_Role");
                }
                return _T_Role;
            }
        }
        private ObjectSet<T_Role> _T_Role;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_User_Role> T_User_Role
        {
            get
            {
                if ((_T_User_Role == null))
                {
                    _T_User_Role = base.CreateObjectSet<T_User_Role>("T_User_Role");
                }
                return _T_User_Role;
            }
        }
        private ObjectSet<T_User_Role> _T_User_Role;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_Articles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Articles(T_Articles t_Articles)
        {
            base.AddObject("T_Articles", t_Articles);
        }
    
        /// <summary>
        /// 用于向 T_Categories EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Categories(T_Categories t_Categories)
        {
            base.AddObject("T_Categories", t_Categories);
        }
    
        /// <summary>
        /// 用于向 T_Links EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Links(T_Links t_Links)
        {
            base.AddObject("T_Links", t_Links);
        }
    
        /// <summary>
        /// 用于向 T_Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Users(T_Users t_Users)
        {
            base.AddObject("T_Users", t_Users);
        }
    
        /// <summary>
        /// 用于向 T_Action EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Action(T_Action t_Action)
        {
            base.AddObject("T_Action", t_Action);
        }
    
        /// <summary>
        /// 用于向 T_Action_Role EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Action_Role(T_Action_Role t_Action_Role)
        {
            base.AddObject("T_Action_Role", t_Action_Role);
        }
    
        /// <summary>
        /// 用于向 T_Role EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Role(T_Role t_Role)
        {
            base.AddObject("T_Role", t_Role);
        }
    
        /// <summary>
        /// 用于向 T_User_Role EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_User_Role(T_User_Role t_User_Role)
        {
            base.AddObject("T_User_Role", t_User_Role);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Action : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Action 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="controllername">controllername 属性的初始值。</param>
        public static T_Action CreateT_Action(global::System.Int32 id, global::System.String controllername)
        {
            T_Action t_Action = new T_Action();
            t_Action.id = id;
            t_Action.controllername = controllername;
            return t_Action;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String controllername
        {
            get
            {
                return _controllername;
            }
            set
            {
                OncontrollernameChanging(value);
                ReportPropertyChanging("controllername");
                _controllername = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("controllername");
                OncontrollernameChanged();
            }
        }
        private global::System.String _controllername;
        partial void OncontrollernameChanging(global::System.String value);
        partial void OncontrollernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String actionname
        {
            get
            {
                return _actionname;
            }
            set
            {
                OnactionnameChanging(value);
                ReportPropertyChanging("actionname");
                _actionname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("actionname");
                OnactionnameChanged();
            }
        }
        private global::System.String _actionname;
        partial void OnactionnameChanging(global::System.String value);
        partial void OnactionnameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Action_Role_T_Action", "T_Action_Role")]
        public EntityCollection<T_Action_Role> T_Action_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Action_Role>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Action_Role>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action_Role", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Action_Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Action_Role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Action_Role 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static T_Action_Role CreateT_Action_Role(global::System.Int32 id)
        {
            T_Action_Role t_Action_Role = new T_Action_Role();
            t_Action_Role.id = id;
            return t_Action_Role;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> aid
        {
            get
            {
                return _aid;
            }
            set
            {
                OnaidChanging(value);
                ReportPropertyChanging("aid");
                _aid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aid");
                OnaidChanged();
            }
        }
        private Nullable<global::System.Int32> _aid;
        partial void OnaidChanging(Nullable<global::System.Int32> value);
        partial void OnaidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rid
        {
            get
            {
                return _rid;
            }
            set
            {
                OnridChanging(value);
                ReportPropertyChanging("rid");
                _rid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rid");
                OnridChanged();
            }
        }
        private Nullable<global::System.Int32> _rid;
        partial void OnridChanging(Nullable<global::System.Int32> value);
        partial void OnridChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Action_Role_T_Action", "T_Action")]
        public T_Action T_Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Action>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Action>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Action> T_ActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Action>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Action>("DB_CMSModel.FK_T_Action_Role_T_Action", "T_Action", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Action_Role_T_Role", "T_Role")]
        public T_Role T_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Role").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Role> T_RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Role", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Articles : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Articles 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="body">body 属性的初始值。</param>
        /// <param name="createtime">createtime 属性的初始值。</param>
        public static T_Articles CreateT_Articles(global::System.Int32 id, global::System.String title, global::System.String body, global::System.DateTime createtime)
        {
            T_Articles t_Articles = new T_Articles();
            t_Articles.id = id;
            t_Articles.title = title;
            t_Articles.body = body;
            t_Articles.createtime = createtime;
            return t_Articles;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @abstract
        {
            get
            {
                return _abstract;
            }
            set
            {
                OnabstractChanging(value);
                ReportPropertyChanging("abstract");
                _abstract = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("abstract");
                OnabstractChanged();
            }
        }
        private global::System.String _abstract;
        partial void OnabstractChanging(global::System.String value);
        partial void OnabstractChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String from
        {
            get
            {
                return _from;
            }
            set
            {
                OnfromChanging(value);
                ReportPropertyChanging("from");
                _from = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("from");
                OnfromChanged();
            }
        }
        private global::System.String _from;
        partial void OnfromChanging(global::System.String value);
        partial void OnfromChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cateid
        {
            get
            {
                return _cateid;
            }
            set
            {
                OncateidChanging(value);
                ReportPropertyChanging("cateid");
                _cateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cateid");
                OncateidChanged();
            }
        }
        private Nullable<global::System.Int32> _cateid;
        partial void OncateidChanging(Nullable<global::System.Int32> value);
        partial void OncateidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private global::System.DateTime _createtime;
        partial void OncreatetimeChanging(global::System.DateTime value);
        partial void OncreatetimeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Articles_T_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Articles_T_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Articles_T_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Articles_T_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("DB_CMSModel.FK_T_Articles_T_Users", "T_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Categories : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Categories 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="parentid">parentid 属性的初始值。</param>
        public static T_Categories CreateT_Categories(global::System.Int32 id, global::System.String name, global::System.Int32 parentid)
        {
            T_Categories t_Categories = new T_Categories();
            t_Categories.id = id;
            t_Categories.name = name;
            t_Categories.parentid = parentid;
            return t_Categories;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private global::System.Int32 _parentid;
        partial void OnparentidChanging(global::System.Int32 value);
        partial void OnparentidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createtime;
        partial void OncreatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreatetimeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Categories_T_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Categories_T_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Categories_T_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_Categories_T_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("DB_CMSModel.FK_T_Categories_T_Users", "T_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Links")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Links : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Links 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="url">url 属性的初始值。</param>
        public static T_Links CreateT_Links(global::System.Int32 id, global::System.String name, global::System.String url)
        {
            T_Links t_Links = new T_Links();
            t_Links.id = id;
            t_Links.name = name;
            t_Links.url = url;
            return t_Links;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createtime;
        partial void OncreatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreatetimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Role 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        public static T_Role CreateT_Role(global::System.Int32 id, global::System.String name)
        {
            T_Role t_Role = new T_Role();
            t_Role.id = id;
            t_Role.name = name;
            return t_Role;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Action_Role_T_Role", "T_Action_Role")]
        public EntityCollection<T_Action_Role> T_Action_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Action_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Action_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Action_Role>("DB_CMSModel.FK_T_Action_Role_T_Role", "T_Action_Role", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_User_Role_T_Role", "T_User_Role")]
        public EntityCollection<T_User_Role> T_User_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_User_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_User_Role", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_User_Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User_Role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_User_Role 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static T_User_Role CreateT_User_Role(global::System.Int32 id)
        {
            T_User_Role t_User_Role = new T_User_Role();
            t_User_Role.id = id;
            return t_User_Role;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rid
        {
            get
            {
                return _rid;
            }
            set
            {
                OnridChanging(value);
                ReportPropertyChanging("rid");
                _rid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rid");
                OnridChanged();
            }
        }
        private Nullable<global::System.Int32> _rid;
        partial void OnridChanging(Nullable<global::System.Int32> value);
        partial void OnridChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_User_Role_T_Role", "T_Role")]
        public T_Role T_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_Role").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Role> T_RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Role>("DB_CMSModel.FK_T_User_Role_T_Role", "T_Role", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_User_Role_T_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_User_Role_T_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_User_Role_T_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("DB_CMSModel.FK_T_User_Role_T_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("DB_CMSModel.FK_T_User_Role_T_Users", "T_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_CMSModel", Name="T_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Users : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Users 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="username">username 属性的初始值。</param>
        /// <param name="password">password 属性的初始值。</param>
        /// <param name="salt">salt 属性的初始值。</param>
        /// <param name="createtime">createtime 属性的初始值。</param>
        /// <param name="type">type 属性的初始值。</param>
        public static T_Users CreateT_Users(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String salt, global::System.DateTime createtime, global::System.Int32 type)
        {
            T_Users t_Users = new T_Users();
            t_Users.id = id;
            t_Users.username = username;
            t_Users.password = password;
            t_Users.salt = salt;
            t_Users.createtime = createtime;
            t_Users.type = type;
            return t_Users;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salt
        {
            get
            {
                return _salt;
            }
            set
            {
                OnsaltChanging(value);
                ReportPropertyChanging("salt");
                _salt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salt");
                OnsaltChanged();
            }
        }
        private global::System.String _salt;
        partial void OnsaltChanging(global::System.String value);
        partial void OnsaltChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private global::System.DateTime _createtime;
        partial void OncreatetimeChanging(global::System.DateTime value);
        partial void OncreatetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastlogintime
        {
            get
            {
                return _lastlogintime;
            }
            set
            {
                OnlastlogintimeChanging(value);
                ReportPropertyChanging("lastlogintime");
                _lastlogintime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastlogintime");
                OnlastlogintimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastlogintime;
        partial void OnlastlogintimeChanging(Nullable<global::System.DateTime> value);
        partial void OnlastlogintimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastloginip
        {
            get
            {
                return _lastloginip;
            }
            set
            {
                OnlastloginipChanging(value);
                ReportPropertyChanging("lastloginip");
                _lastloginip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastloginip");
                OnlastloginipChanged();
            }
        }
        private global::System.String _lastloginip;
        partial void OnlastloginipChanging(global::System.String value);
        partial void OnlastloginipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastloginarea
        {
            get
            {
                return _lastloginarea;
            }
            set
            {
                OnlastloginareaChanging(value);
                ReportPropertyChanging("lastloginarea");
                _lastloginarea = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastloginarea");
                OnlastloginareaChanged();
            }
        }
        private global::System.String _lastloginarea;
        partial void OnlastloginareaChanging(global::System.String value);
        partial void OnlastloginareaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int32 _type;
        partial void OntypeChanging(global::System.Int32 value);
        partial void OntypeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Articles_T_Users", "T_Articles")]
        public EntityCollection<T_Articles> T_Articles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Articles>("DB_CMSModel.FK_T_Articles_T_Users", "T_Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Articles>("DB_CMSModel.FK_T_Articles_T_Users", "T_Articles", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_Categories_T_Users", "T_Categories")]
        public EntityCollection<T_Categories> T_Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Categories>("DB_CMSModel.FK_T_Categories_T_Users", "T_Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Categories>("DB_CMSModel.FK_T_Categories_T_Users", "T_Categories", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_CMSModel", "FK_T_User_Role_T_Users", "T_User_Role")]
        public EntityCollection<T_User_Role> T_User_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User_Role>("DB_CMSModel.FK_T_User_Role_T_Users", "T_User_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User_Role>("DB_CMSModel.FK_T_User_Role_T_Users", "T_User_Role", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
